### ISSUE TITLE
Video streaming is not correctly encoded?

### ISSUE THREAD

**Issue by angel-ayala** [Andreas1331/android-webrtc-dji#2]
Hi, this is a very good code to stream DJI drone camera feed.
I implemented your code in [this repo](https://github.com/angel-ayala/DJIVideoStreamDecodingSample), based on the [DJIVideoStreamDecode example](https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample/) and I'm able to get the video feed on a NodeJS client side.
However, the video stream appears to have a bad codification on the Android side because the frames aren't presented in full color.
At first look appears to be in grayscale, but if I point to a white paper sheet I'm able to see a spatial offset of the same sheet twice. One, appears on the top that apparently with a magenta color, and the second, appears on the bottom with the cyan colors. I don't know how correctly explain this, but definitively there is a problem with the codec.

Do you experienced any of this? There is any special care with the DJICodecManager maybe? What should I check to ensure a well functioning?

Any comments will be very helpful. Thanks in advance.

**Comment by angel-ayala** [comment]
I payed attention and you mentioned to check the codec capabilities, and I used the I420 and it works.

**Comment by Andreas1331** [comment]
Awesome you figured it out! I was away, so apologies for the late response.
